### ISSUE TITLE
hardlinks fail with EXDEV (Invalid cross-device link)

### ISSUE THREAD

**Issue by mulle-nat** [marty1885/landlock-unveil#2]
When running under `landlock-unveil`, `ln` can't create hardlinks in subdirectories: 

``` sh
touch x
mkdir foo
lljail -rx / -rwcx "${PWD}" -- /usr/bin/ln x foo/z
```

This will fail with a cross-device link error.  I don't know, if this is really a problem of landlock-unveil or rather the kernel though.

**Comment by l0kod** [comment]
For such link to work, the `LANDLOCK_ACCESS_FS_REFER` right needs to be [handled by the Landlock ruleset](https://github.com/marty1885/landlock-unveil/blob/master/llunveil/llunveil.c#L113) and [allowed for all rules](https://github.com/marty1885/landlock-unveil/blob/master/llunveil/llunveil.c#L176). You also need to have a compatible kernel (>= 5.19 if there is no backport). See https://docs.kernel.org/userspace-api/landlock.html#file-renaming-and-linking-abi-2

**Comment by marty1885** [comment]
Thanks @l0kod! I was looking through the docs and scratching my head. I'll come up with some patch this weekend or shortly after. 

Kinda traveling this week

**Comment by marty1885** [comment]
Links should work after the latest PR and with kernel supporting ABIv2. Feel free to reopen

**Comment by mulle-nat** [comment]
Looks good to me!
